name: Update Visitor Count

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Visitor Count
        run: curl -s https://api.countapi.xyz/hit/FIRandZAH/encode
        
